const { MongoClient } = require("mongodb");

MongoClient.connect(
  "mongodb://127.0.0.1/27017",
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  },
  (error, client) => {
    if (error) {
      return console.log("Unable");
    }

    const db = client.db("FlightDB");

    // db.collection("flight").insertMany(
    //   [
    //     {
    //       origin: "Mumbai",
    //       destination: "Delhi",
    //       date: "01/06/2021",
    //       depTime: "5:00",
    //       arrTime: "8:30",
    //       flightNo: "IND46",
    //       name: "Indigo",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Mumbai",
    //       destination: "Banglore",
    //       date: "01/06/2021",
    //       depTime: "6:00",
    //       arrTime: "9:30",
    //       flightNo: "IND47",
    //       name: "Indigo",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Mumbai",
    //       destination: "Pune",
    //       date: "01/06/2021",
    //       depTime: "7:30",
    //       arrTime: "8:45",
    //       flightNo: "GO-107",
    //       name: "GOAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Mumbai",
    //       destination: "Nagpur",
    //       date: "01/06/2021",
    //       depTime: "16:00",
    //       arrTime: "18:00",
    //       flightNo: "GO-108",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Pune",
    //       destination: "Delhi",
    //       date: "01/06/2021",
    //       depTime: "13:00",
    //       arrTime: "15:00",
    //       flightNo: "IND47",
    //       name: "Indigo",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Pune",
    //       destination: "Banglore",
    //       date: "01/06/2021",
    //       depTime: "16:30",
    //       arrTime: "19:10",
    //       flightNo: "IND48",
    //       name: "Indigo",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Pune",
    //       destination: "Nagpur",
    //       date: "01/06/2021",
    //       depTime: "20:30",
    //       arrTime: "21:15",
    //       flightNo: "GO-109",
    //       name: "GOAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Pune",
    //       destination: "Mumbai",
    //       date: "01/06/2021",
    //       depTime: "22:00",
    //       arrTime: "23:00",
    //       flightNo: "GO-110",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Pune",
    //       destination: "Indore",
    //       date: "01/06/2021",
    //       depTime: "21:00",
    //       arrTime: "19:00",
    //       flightNo: "GO-310",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Pune",
    //       destination: "Bhopal",
    //       date: "01/06/2021",
    //       depTime: "21:00",
    //       arrTime: "20:00",
    //       flightNo: "GO-320",
    //       name: "GoAir",
    //       price: 8000,
    //     },

    //     {
    //       origin: "Banglore",
    //       destination: "Delhi",
    //       date: "01/06/2021",
    //       depTime: "4:00",
    //       arrTime: "6:00",
    //       flightNo: "IND50",
    //       name: "Indigo",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Banglore",
    //       destination: "Pune",
    //       date: "01/06/2021",
    //       depTime: "20:30",
    //       arrTime: "22:10",
    //       flightNo: "IND51",
    //       name: "Indigo",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Banglore",
    //       destination: "Nagpur",
    //       date: "01/06/2021",
    //       depTime: "16:30",
    //       arrTime: "22:15",
    //       flightNo: "GO-109",
    //       name: "GOAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Banglore",
    //       destination: "Mumbai",
    //       date: "01/06/2021",
    //       depTime: "10:00",
    //       arrTime: "11:30",
    //       flightNo: "GO-112",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Banglore",
    //       destination: "Mumbai",
    //       date: "01/06/2021",
    //       depTime: "13:00",
    //       arrTime: "15:30",
    //       flightNo: "GO-114",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Indore",
    //       destination: "Pune",
    //       date: "01/06/2021",
    //       depTime: "6:00",
    //       arrTime: "9:40",
    //       flightNo: "GO-116",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Indore",
    //       destination: "Mumbai",
    //       date: "01/06/2021",
    //       depTime: "13:00",
    //       arrTime: "16:00",
    //       flightNo: "GO-117",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Indore",
    //       destination: "Bhopal",
    //       date: "01/06/2021",
    //       depTime: "22:00",
    //       arrTime: "23:40",
    //       flightNo: "GO-119",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Bhopal",
    //       destination: "Pune",
    //       date: "01/06/2021",
    //       depTime: "7:00",
    //       arrTime: "9:40",
    //       flightNo: "GO-118",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Bhopal",
    //       destination: "Mumbai",
    //       date: "01/06/2021",
    //       depTime: "13:00",
    //       arrTime: "16:00",
    //       flightNo: "GO-120",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //     {
    //       origin: "Bhopal",
    //       destination: "Indore",
    //       date: "01/06/2021",
    //       depTime: "23:00",
    //       arrTime: "23:45",
    //       flightNo: "GO-122",
    //       name: "GoAir",
    //       price: 8000,
    //     },
    //   ],
    //   (error, result) => {
    //     if (error) {
    //       return console.log("Fault");
    //     }
    //     console.log(result.ops);
    //   }
    // );
  }
);

module.exports = db;
